services:
  backend:
    build: ./backend
    container_name: fun-backend-dev
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=Host=${DB_HOST};Port=${DB_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    depends_on:
      - db
    networks:
      - fun-net

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: frontend/Dockerfile
  #   container_name: fun-frontend-dev
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env
  #   environment:
  #     - VITE_API_URL=${VITE_API_URL}
  #   depends_on:
  #     - backend
  #   networks:
  #     - fun-net

  db:
    image: postgres:15
    container_name: fun-db-dev
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fun-net

  nginx:
    image: nginx:alpine
    container_name: fun-nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/ssl/certs
    depends_on:
      - backend
      # - frontend
    networks:
      - fun-net

volumes:
  postgres_data:

networks:
  fun-net:
    driver: bridge